### ISSUE TITLE
@xfx98 我不太理解你的意思，你单独开个 `issue` 吧，截图说明下呢，这个评论太长了，不便于讨论。

### ISSUE THREAD

**Issue by xfx98** [blinkfox/blinkfox.github.io#79]
@xfx98 我不太理解你的意思，你单独开个 `issue` 吧，截图说明下呢，这个评论太长了，不便于讨论。

_Originally posted by @blinkfox in https://github.com/blinkfox/blinkfox.github.io/issues/26#issuecomment-505068669_
-------
emmm解决了，文档解析格式问题，标题在目录显示，点击没导航到目标锚记

**Comment by blinkfox** [comment]
解决了就行，那我关掉这个 `issue`。
